import 'package:flutter/material.dart';

const emailIcon = Icons.email_outlined;
const passowrdIcon = Icons.lock_outlined;
const eyeIcon = Icons.visibility_outlined;
const expndIcon = Icons.expand;
const arrowBackIcon = Icons.arrow_back;
const dashboardIcon = Icons.dashboard_outlined;
const walletIcon = Icons.account_balance_wallet_outlined;
const cardsIcon = Icons.credit_card_outlined;
const settingsIcon = Icons.settings_outlined;
const arrowForward = Icons.east_outlined;
const accountBalanceWallet = Icons.account_balance_wallet_outlined;
const inputIcon = Icons.input_outlined;
const driveFileIcon = Icons.drive_file_move_rtl_outlined;
const cancelIcon = Icons.cancel;
const trendingIcon = Icons.trending_up;
const accountBalance = Icons.account_balance;
const expandMore = Icons.expand_more;
const navigatNext = Icons.navigate_next;
const supervisorAccount = Icons.supervisor_account;
const locationOnOutlined = Icons.location_on_outlined;
const accountBoxOutlined = Icons.account_box_outlined;
const dialPad = Icons.dialpad;
const verifiedUser = Icons.verified_user_outlined;
