// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4eGit_219c9TGNDfjnLBllc9kyf1bwLc',
    appId: '1:524599079755:web:544769c27f2d514bae2ece',
    messagingSenderId: '524599079755',
    projectId: 'shelter-105fe',
    authDomain: 'shelter-105fe.firebaseapp.com',
    storageBucket: 'shelter-105fe.appspot.com',
    measurementId: 'G-2RFT8ZB23Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuUFBbNomA_9KH_MQ_V3e-QOWO7U1qHX8',
    appId: '1:524599079755:android:d43183b0b180ca29ae2ece',
    messagingSenderId: '524599079755',
    projectId: 'shelter-105fe',
    storageBucket: 'shelter-105fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTYobohNxAc38ZMMCellNe6ekWtFUULho',
    appId: '1:524599079755:ios:820699916c9ebc49ae2ece',
    messagingSenderId: '524599079755',
    projectId: 'shelter-105fe',
    storageBucket: 'shelter-105fe.appspot.com',
    iosBundleId: 'com.example.shelter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTYobohNxAc38ZMMCellNe6ekWtFUULho',
    appId: '1:524599079755:ios:9329f56be4520596ae2ece',
    messagingSenderId: '524599079755',
    projectId: 'shelter-105fe',
    storageBucket: 'shelter-105fe.appspot.com',
    iosBundleId: 'com.example.shelter.RunnerTests',
  );
}
